version: '3.8'

services:
  freerdp:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: freerdp_container
    ports:
      - "3389:3389"   # RDP
      - "5901:5901"   # VNC
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ../shared/user-data:/home/user/shared
    restart: unless-stopped
