version: '3.9'

services:
  free-rdp:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3389:3389"
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - UID=${UID}
      - GID=${GID}
      - TZ=${TZ}
    volumes:
      - ./shared/user-data:/home/${USERNAME}/shared
    restart: unless-stopped
