version: "3.8"

services:
  freerdp:
    container_name: freerdp-desktop
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "3389:3389"   # RDP
      - "5901:5901"   # VNC
      - "6080:6080"   # noVNC (HTTP)
    volumes:
      - x11-data:/tmp/.X11-unix
      - crd-config:/etc/crd
    environment:
      - DISPLAY=:1
      - USER=root
      - PASSWORD=secret
    restart: unless-stopped

volumes:
  x11-data:
  crd-config:
