---
- name: Deploy and run FreeRDP with web port start after exit
  hosts: all
  become: yes
  vars:
    project_path: /opt/free-rdp
    compose_dir: "{{ project_path }}/compose"
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present

    - name: Create project directory
      file:
        path: "{{ project_path }}"
        state: directory
        mode: '0755'

    - name: Copy project files to server
      synchronize:
        src: ./free-rdp/
        dest: "{{ project_path }}/"
        recursive: yes
        delete: yes

    - name: Start FreeRDP containers via docker-compose
      community.docker.docker_compose:
        project_src: "{{ compose_dir }}"
        state: present
        restarted: yes

- name: Wait for FreeRDP container to stop (simulate waiting for exit)
  shell: |
    CONTAINER_NAME=$(docker-compose -f {{ compose_dir }}/docker-compose.yml ps -q free-rdp)
    while [ "$(docker inspect -f '{{ '{{' }}.State.Running{{ '}}' }}' $CONTAINER_NAME)" == "true" ]; do
      sleep 5
    done
  args:
    executable: /bin/bash


    - name: Start web server after FreeRDP container exits
      service:
        name: apache2
        state: started
        enabled: yes
