name: Deploy FreeRDP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible community.docker

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/free-rdp.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
