name: CI free-rdp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Lint shell scripts
      uses: koalaman/shellcheck@v1
      with:
        files: docker/entrypoint.sh

    - name: Lint YAML files
      uses: ibiqlik/action-yamllint@v1
      with:
        files: |
          compose/docker-compose.yml
          config/xrdp.ini
          config/sesman.ini
          
    - name: Checkout repository
      uses: koalaman/shellcheck@v1

    - name: Set up Docker Buildx (для продвинутого билда, можно опустить)
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t free-rdp-test -f docker/Dockerfile docker/

    - name: Run docker-compose up (in detached mode)
      run: |
        docker-compose -f compose/docker-compose.yml up -d

    - name: Wait and test container is running
      run: |
        sleep 9999999999
        docker ps | grep free-rdp || (echo "Container not running" && exit 1)

    - name: Tear down docker-compose
      run: docker-compose -f compose/docker-compose.yml down

    - name: Lint shell scripts
      uses: ludeeus/action-shellcheck@v1
      with:
        files: |
          docker/entrypoint.sh

    - name: Lint YAML files
      uses: ibiqlik/action-yamllint@v1
      with:
        files: |
          compose/docker-compose.yml
          config/xrdp.ini
          config/sesman.ini
